#!/usr/bin/env python
import os,sys,glob,json

master_ortholog_dict=dict()
for file in glob.glob("*_TAIR10"):
    with open(file) as fh:
        header=1
        for line in fh.readlines():
            if(header==1):
                header-=1
                continue

            line=line.strip('\r\n')
            (query_species_orthologs,athaliana_orthologs)=line.split('\t')

            # each line generated by inParanoid can have multiple orthologs
            # each paired with a "score" as generated by inParanoid
            # Query species
            input = query_species_orthologs.split()
            query_species = ""
            query_proteins = list()
            for spp_protein_score in (" ".join((gene, coeff)) for gene,coeff in zip(input[:-1:2], input[1::2])):
                (spp_protein,score)=spp_protein_score.split()
                (spp,protein)=spp_protein.split(':',1)

                if(spp not in master_ortholog_dict):
                    master_ortholog_dict[spp]=dict()
                if(protein not in master_ortholog_dict[spp]):
                    master_ortholog_dict[spp][protein]=dict()
                    
                query_species = spp
                query_proteins.append(protein)

            # Athaliana orthologs
            input = athaliana_orthologs.split()

            for spp_protein_score in (" ".join((gene, coeff)) for gene,coeff in zip(input[:-1:2], input[1::2])):
                (spp_protein,score)=spp_protein_score.split()
                (spp,protein)=spp_protein.split(':',1)

                for q_prot in query_proteins:
                    master_ortholog_dict[query_species][q_prot][protein]=score

with open("Phytozome_Ortholog_Mapping.json","w") as ofh:
    json.dump(master_ortholog_dict,ofh,indent=4)
